server:
  port: 12100
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE
    driver-class-name: org.h2.Driver
    name: sa
    password: sa
  kafka:
    bootstrap-servers: "localhost:29092"
    consumer:
      group-id: customerGroup
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties: 
        spring:
          json:
            trusted:
              packages: "*"
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer