CREATE TABLE CUSTOMER (
	CUSTOMER_ID NUMBER PRIMARY KEY,
	CUSTOMER_NAME VARCHAR(50) NOT NULL,
	CUSTOMER_NAME_KANA VARCHAR(50) NOT NULL,
	CUSTOMER_GENDER CHAR(1) NOT NULL,
	BOOK_COUNT INTEGER NOT NULL,
	CUSTOMER_BIRTHDAY CHAR(8) NOT NULL,
	TX_STATUS VARCHAR(10) NOT NULL
)
;
