CREATE TABLE IF NOT EXISTS BOOK_ORDER (
	ORDER_ID NUMBER PRIMARY KEY,
	CUSTOMER_ID NUMBER NOT NULL,
	ORDER_DATE TIMESTAMP NOT NULL,
	TX_STATUS VARCHAR(10) NOT NULL
)
;

CREATE TABLE IF NOT EXISTS ORDER_DETAIL (
	ORDER_ID NUMBER NOT NULL,
	ORDER_ASC NUMBER NOT NULL,
	BOOK_ID NUMBER NOT NULL,
	ORDER_COUNT NUMBER NOT NULL,
	TX_STATUS VARCHAR(10) NOT NULL,
	PRIMARY KEY(ORDER_ID, BOOK_ID)
)
;

CREATE SEQUENCE IF NOT EXISTS ORDER_ID_SEQ { 
	START WITH 4
	INCREMENT BY 1
	CYCLE
}